### ISSUE TITLE
Code Comments for R Journal Review

### ISSUE THREAD

**Issue by leeper** [shuowencs/SortedEffects#1]
I am a reviewer of your manuscript for R Journal and am submitting a few comments on code here.

**Comment by leeper** [comment]
When you have a constrained set of character string values that are allowed for a function argument, like in `method` here (https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L44), you can specify them in the function signature as a vector `c("ols", "logit", ...)` and then use `match.arg()` to retrieve the default and validate a user-supplied value against that list of allowed values.

**Comment by leeper** [comment]
Rather than giving errors that ask for a correct argument value, the errors might be improved by saying what values are allowed (e.g., https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L48 and subsequent lines).

**Comment by leeper** [comment]
For bootstrap draws, why set a default value that you don't personally recommend? https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L26

**Comment by leeper** [comment]
Moving auxiliary or utility functions to a separate file (but not exporting them) allows you to test their behavior more easily than embedding them in another function definition: https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L134

**Comment by leeper** [comment]
Explicitly return the `output` object: https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L130

**Comment by leeper** [comment]
Missing variable definitions for `wage2015` data: https://github.com/shuowencs/SortedEffects/blob/master/R/data.R#L33

**Comment by leeper** [comment]
If plotting functions are meant to be convenient quick-use tools for the interactive user, I would be inclined to set default values to arguments like `xlab` and `ylab` so it's clear what is being presented: https://github.com/shuowencs/SortedEffects/blob/master/R/u.Subpop.R#L190

**Comment by leeper** [comment]
It's generally bad practice to set options() inside functions (https://github.com/shuowencs/SortedEffects/blob/master/R/PEestimate.R#L17). If you do it, you should reset to the previous value.

**Comment by shuowencs** [comment]
@leeper Hi Dr. Leeper, thank you very much for your comments. I will revise the package and vignette based on your suggestions.
